"""CLI backend contracts and shared errors."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


class UnsupportedInModeError(RuntimeError):
    """Raised when a command is unavailable in the selected CLI mode."""


class DeviceBackend(Protocol):
    def list(self, *, status: str | None = None) -> Any: ...
    def pending(self) -> Any: ...
    def validate(self, *, index: int, role: str) -> Any: ...
    def approve(self, *, device_id: str, role: str) -> Any: ...
    def revoke(self, *, device_id: str) -> Any: ...
    def issue_token(self, *, device_id: str, ttl: int) -> Any: ...


class CustomerBackend(Protocol):
    def list(self, *, search: str | None = None) -> Any: ...
    def duplicates(self) -> Any: ...
    def create(self, **kwargs: Any) -> Any: ...
    def update(self, customer_id: str, **kwargs: Any) -> Any: ...
    def usage(self, customer_id: str) -> Any: ...
    def merge(self, customer_id: str, *, into: str) -> Any: ...
    def delete(self, customer_id: str) -> Any: ...


class BillingBackend(Protocol):
    def list(self, *, search: str | None = None) -> Any: ...
    def duplicates(self) -> Any: ...
    def create(self, **kwargs: Any) -> Any: ...
    def update(self, billing_profile_id: str, **kwargs: Any) -> Any: ...
    def usage(self, billing_profile_id: str) -> Any: ...
    def merge(self, billing_profile_id: str, *, into: str) -> Any: ...
    def delete(self, billing_profile_id: str) -> Any: ...


class JobBackend(Protocol):
    def create(self, **kwargs: Any) -> Any: ...
    def update(self, job_ref: str, **kwargs: Any) -> Any: ...
    def inspect(self, *, job_ref: str) -> Any: ...
    def list_assignments(self, *, raw: bool = False) -> Any: ...
    def assign(self, *, job_ref: str, device_id: str) -> Any: ...
    def unassign(self, *, job_ref: str) -> Any: ...
    def set_status(
        self,
        *,
        job_ref: str,
        status: str,
        round_id: str | None = None,
        round_status: str | None = None,
    ) -> Any: ...
    def unlock(
        self,
        *,
        job_ref: str,
        round_id: str | None = None,
        device_id: str | None = None,
    ) -> Any: ...


class RoundBackend(Protocol):
    def create(self, *, job_ref: str) -> Any: ...
    def manifest_get(self, *, job_ref: str, round_id: str) -> Any: ...
    def manifest_set(self, *, job_ref: str, round_id: str, items: list[dict[str, Any]]) -> Any: ...
    def submit(self, *, job_ref: str, round_id: str, payload: dict[str, Any] | None) -> Any: ...
    def reprocess(self, *, job_ref: str, round_id: str) -> Any: ...
    def reopen(self, *, job_id: str, round_id: str) -> Any: ...
    def inspect(self, *, job_ref: str, round_id: str) -> Any: ...


class ReviewBackend(Protocol):
    def inspect(self, *, job_ref: str, round_id: str) -> Any: ...


class FinalBackend(Protocol):
    def inspect(self, *, job_ref: str) -> Any: ...
    def set_final(self, *, job_ref: str, payload: dict[str, Any], geojson_payload: dict[str, Any] | None) -> Any: ...
    def set_correction(self, *, job_ref: str, payload: dict[str, Any], geojson_payload: dict[str, Any] | None) -> Any: ...


class ArtifactBackend(Protocol):
    def fetch(self, *, job_ref: str, kind: str) -> Any: ...


class TreeBackend(Protocol):
    def identify(
        self,
        *,
        image_paths: list[str],
        organs: list[str] | None = None,
        project: str | None = None,
        include_related_images: bool = False,
        no_reject: bool = False,
        nb_results: int | None = None,
        lang: str | None = None,
    ) -> Any: ...


class NetBackend(Protocol):
    def ipv4(self) -> Any: ...
    def ipv6(self) -> Any: ...


@dataclass(frozen=True)
class CliBackendBundle:
    mode_name: str
    device: DeviceBackend
    customer: CustomerBackend
    billing: BillingBackend
    job: JobBackend
    round: RoundBackend
    review: ReviewBackend
    final: FinalBackend
    artifact: ArtifactBackend
    tree: TreeBackend
    net: NetBackend
