"""baseline schema

Revision ID: d5a83498da59
Revises: 
Create Date: 2026-03-17 22:03:32.497523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5a83498da59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billing_code', sa.String(length=32), nullable=False),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('billing_contact_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_preference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_profiles_billing_code'), 'billing_profiles', ['billing_code'], unique=True)
    op.create_index(op.f('ix_billing_profiles_billing_name'), 'billing_profiles', ['billing_name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('arborist', 'admin', name='devicerole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'revoked', name='devicestatus'), nullable=False),
    sa.Column('profile_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=True)
    op.create_table('runtime_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('counter_key', sa.String(length=128), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_counters_counter_key'), 'runtime_counters', ['counter_key'], unique=True)
    op.create_table('runtime_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_key', sa.String(length=255), nullable=False),
    sa.Column('profile_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_profiles_identity_key'), 'runtime_profiles', ['identity_key'], unique=True)
    op.create_table('device_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('arborist', 'admin', name='devicerole'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_device_id'), 'device_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_expires_at'), 'device_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_tokens_revoked'), 'device_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_table('trees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('tree_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'tree_number', name='uq_trees_customer_tree_number')
    )
    op.create_index(op.f('ix_trees_customer_id'), 'trees', ['customer_id'], unique=False)
    op.create_index(op.f('ix_trees_tree_number'), 'trees', ['tree_number'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('job_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('billing_profile_id', sa.Uuid(), nullable=True),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('tree_id', sa.Uuid(), nullable=True),
    sa.Column('tree_number', sa.Integer(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('job_address', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('tree_species', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'draft', 'submitted', 'review_returned', 'archived', 'failed', name='jobstatus'), nullable=False),
    sa.Column('latest_round_id', sa.String(length=128), nullable=True),
    sa.Column('latest_round_status', sa.Enum('draft', 'submitted', 'review_returned', 'failed', name='roundstatus'), nullable=True),
    sa.Column('profile_identity', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('final_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('correction_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['billing_profile_id'], ['billing_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_billing_profile_id'), 'jobs', ['billing_profile_id'], unique=False)
    op.create_index(op.f('ix_jobs_customer_id'), 'jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_job_number'), 'jobs', ['job_number'], unique=True)
    op.create_index(op.f('ix_jobs_operator_id'), 'jobs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tree_id'), 'jobs', ['tree_id'], unique=False)
    op.create_index(op.f('ix_jobs_tree_number'), 'jobs', ['tree_number'], unique=False)
    op.create_table('job_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_job_assignments_job_id')
    )
    op.create_index(op.f('ix_job_assignments_device_id'), 'job_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_job_id'), 'job_assignments', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('device_registered', 'device_approved', 'token_issued', 'job_created', 'job_assigned', 'round_created', 'round_submitted', 'round_reprocessed', 'review_returned', 'final_generated', 'correction_generated', 'status_changed', name='eventtype'), nullable=False),
    sa.Column('actor_identity', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('job_finals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'kind', name='uq_job_finals_job_kind')
    )
    op.create_index(op.f('ix_job_finals_job_id'), 'job_finals', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_finals_kind'), 'job_finals', ['kind'], unique=False)
    op.create_table('job_geojson_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'kind', name='uq_job_geojson_exports_job_kind')
    )
    op.create_index(op.f('ix_job_geojson_exports_job_id'), 'job_geojson_exports', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_geojson_exports_kind'), 'job_geojson_exports', ['kind'], unique=False)
    op.create_table('job_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'review_returned', 'failed', name='roundstatus'), nullable=False),
    sa.Column('server_revision_id', sa.String(length=128), nullable=True),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('review_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'round_id', name='uq_job_rounds_job_round_id')
    )
    op.create_index(op.f('ix_job_rounds_job_id'), 'job_rounds', ['job_id'], unique=False)
    op.create_index('ix_job_rounds_job_status', 'job_rounds', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_job_rounds_round_id'), 'job_rounds', ['round_id'], unique=False)
    op.create_index(op.f('ix_job_rounds_status'), 'job_rounds', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('round_pk', sa.Uuid(), nullable=True),
    sa.Column('job_final_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('audio', 'image', 'transcript_txt', 'review_json', 'final_json', 'final_pdf', 'report_pdf', 'report_docx', 'geojson', name='artifactkind'), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_final_id'], ['job_finals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_pk'], ['job_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_final_id'), 'artifacts', ['job_final_id'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_round_pk'), 'artifacts', ['round_pk'], unique=False)
    op.create_table('round_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_pk', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.String(length=128), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('upload_status', sa.Enum('pending', 'uploading', 'uploaded', 'processed', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_pk'], ['job_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_pk', 'image_id', name='uq_round_images_round_image_id')
    )
    op.create_index(op.f('ix_round_images_image_id'), 'round_images', ['image_id'], unique=False)
    op.create_index(op.f('ix_round_images_round_pk'), 'round_images', ['round_pk'], unique=False)
    op.create_index(op.f('ix_round_images_section_id'), 'round_images', ['section_id'], unique=False)
    op.create_index(op.f('ix_round_images_upload_status'), 'round_images', ['upload_status'], unique=False)
    op.create_table('round_recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_pk', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.String(length=128), nullable=False),
    sa.Column('recording_id', sa.String(length=255), nullable=False),
    sa.Column('upload_status', sa.Enum('pending', 'uploading', 'uploaded', 'processed', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_pk'], ['job_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_pk', 'recording_id', name='uq_round_recordings_round_recording_id')
    )
    op.create_index(op.f('ix_round_recordings_recording_id'), 'round_recordings', ['recording_id'], unique=False)
    op.create_index(op.f('ix_round_recordings_round_pk'), 'round_recordings', ['round_pk'], unique=False)
    op.create_index(op.f('ix_round_recordings_section_id'), 'round_recordings', ['section_id'], unique=False)
    op.create_index(op.f('ix_round_recordings_upload_status'), 'round_recordings', ['upload_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_round_recordings_upload_status'), table_name='round_recordings')
    op.drop_index(op.f('ix_round_recordings_section_id'), table_name='round_recordings')
    op.drop_index(op.f('ix_round_recordings_round_pk'), table_name='round_recordings')
    op.drop_index(op.f('ix_round_recordings_recording_id'), table_name='round_recordings')
    op.drop_table('round_recordings')
    op.drop_index(op.f('ix_round_images_upload_status'), table_name='round_images')
    op.drop_index(op.f('ix_round_images_section_id'), table_name='round_images')
    op.drop_index(op.f('ix_round_images_round_pk'), table_name='round_images')
    op.drop_index(op.f('ix_round_images_image_id'), table_name='round_images')
    op.drop_table('round_images')
    op.drop_index(op.f('ix_artifacts_round_pk'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_final_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_job_rounds_status'), table_name='job_rounds')
    op.drop_index(op.f('ix_job_rounds_round_id'), table_name='job_rounds')
    op.drop_index('ix_job_rounds_job_status', table_name='job_rounds')
    op.drop_index(op.f('ix_job_rounds_job_id'), table_name='job_rounds')
    op.drop_table('job_rounds')
    op.drop_index(op.f('ix_job_geojson_exports_kind'), table_name='job_geojson_exports')
    op.drop_index(op.f('ix_job_geojson_exports_job_id'), table_name='job_geojson_exports')
    op.drop_table('job_geojson_exports')
    op.drop_index(op.f('ix_job_finals_kind'), table_name='job_finals')
    op.drop_index(op.f('ix_job_finals_job_id'), table_name='job_finals')
    op.drop_table('job_finals')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_job_assignments_job_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_device_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_jobs_tree_number'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_tree_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_operator_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_number'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_customer_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_billing_profile_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_trees_tree_number'), table_name='trees')
    op.drop_index(op.f('ix_trees_customer_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_revoked'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_expires_at'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_device_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_runtime_profiles_identity_key'), table_name='runtime_profiles')
    op.drop_table('runtime_profiles')
    op.drop_index(op.f('ix_runtime_counters_counter_key'), table_name='runtime_counters')
    op.drop_table('runtime_counters')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_billing_profiles_billing_name'), table_name='billing_profiles')
    op.drop_index(op.f('ix_billing_profiles_billing_code'), table_name='billing_profiles')
    op.drop_table('billing_profiles')
    # ### end Alembic commands ###
